x-base: &base
  image: djangobox/django-docker-box:${PYTHON_VERSION}
  build:
    context: ${DJANGO_PATH}
    dockerfile: ${PWD}/Containerfile
    args:
    - PYTHON_VERSION=${PYTHON_VERSION}
    cache_from:
    - djangobox/django-docker-box:${PYTHON_VERSION}
  volumes:
  - ${DJANGO_PATH}:/tests/django/
  - ./settings.py:/tests/django/tests/settings.py
  entrypoint: bash -c "wait-for-it.sh -s -t 20 $${WAIT_FOR} -- python runtests.py $$@" --

x-mysql-base: &mysql-base
  environment:
  - MYSQL_ALLOW_EMPTY_PASSWORD=1
  - MYSQL_DATABASE=django
  - MYSQL_PASSWORD=django
  - MYSQL_USER=django
  tmpfs:
  - /var/lib/mysql
  deploy:
    mode: global
  restart: unless-stopped

x-postgresql-base: &postgresql-base
  environment:
  - POSTGRES_DB=django
  - POSTGRES_PASSWORD=django
  - POSTGRES_USER=django
  tmpfs:
  - /var/lib/postgresql
  deploy:
    mode: global
  restart: unless-stopped
  command: >-
    -c fsync=off
    -c full_page_writes=off
    -c synchronous_commit=off

x-memcached: &memcached-base
  image: memcached:alpine
  deploy:
    mode: global
  restart: unless-stopped

services:

  # Services: Databases

  mariadb-db:
    <<: *mysql-base
    image: mariadb:${MARIADB_VERSION}

  mysql-db:
    <<: *mysql-base
    image: &mysql-image mysql:${MYSQL_VERSION}

  mysql-gis-db:
    <<: *mysql-base
    image: *mysql-image

  postgresql-db:
    <<: *postgresql-base
    image: postgres:${POSTGRESQL_VERSION}-alpine

  postgresql-gis-db:
    <<: *postgresql-base
    image: postgis/postgis:${POSTGRESQL_VERSION}-${POSTGIS_VERSION}

  # Services: Caches

  memcached:
    <<: *memcached-base

  memcached2:
    <<: *memcached-base

  # Services: Selenium

  chrome-browser:
    image: selenium/standalone-chrome
    deploy:
      mode: global
    restart: unless-stopped
    volumes:
    - /dev/shm:/dev/shm

  firefox-browser:
    image: selenium/standalone-firefox
    deploy:
      mode: global
    restart: unless-stopped
    volumes:
    - /dev/shm:/dev/shm

  # Commands: Tests

  mariadb:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.mysql
    - DATABASE_HOST=mariadb-db
    - WAIT_FOR=mariadb-db:3306
    depends_on:
    - mariadb-db
    - memcached
    - memcached2

  mysql:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.mysql
    - DATABASE_HOST=mysql-db
    - WAIT_FOR=mysql-db:3306
    depends_on:
    - mysql-db
    - memcached
    - memcached2

  postgresql:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.postgresql
    - DATABASE_HOST=postgresql-db
    - WAIT_FOR=postgresql-db:5432
    depends_on:
    - postgresql-db
    - memcached
    - memcached2

  sqlite:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.db.backends.sqlite3
    entrypoint: python runtests.py
    depends_on:
    - memcached
    - memcached2

  # Commands: Tests: GIS

  mysql-gis:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.contrib.gis.db.backends.mysql
    - DATABASE_HOST=mysql-gis-db
    - WAIT_FOR=mysql-gis-db:3306
    depends_on:
    - mysql-gis-db

  postgresql-gis:
    <<: *base
    environment:
    - DATABASE_ENGINE=django.contrib.gis.db.backends.postgis
    - DATABASE_HOST=postgresql-gis-db
    - WAIT_FOR=postgresql-gis-db:5432
    depends_on:
    - postgresql-gis-db

  sqlite-gis:
    <<: *base
    entrypoint: python runtests.py
    environment:
    - DATABASE_ENGINE=django.contrib.gis.db.backends.spatialite

  # Commands: Tests: Selenium

  chrome:
    <<: *base
    command: --selenium=chrome --selenium-hub=http://chrome-browser:4444/wd/hub
    environment:
    - DATABASE_ENGINE=django.db.backends.sqlite3
    - WAIT_FOR=chrome-browser:4444
    depends_on:
      - chrome-browser

  firefox:
    <<: *base
    command: --selenium=firefox --selenium-hub=http://firefox-browser:4444/wd/hub
    environment:
    - DATABASE_ENGINE=django.db.backends.sqlite3
    - WAIT_FOR=firefox-browser:4444
    depends_on:
    - firefox-browser

  # Commands: Other

  docs:
    <<: *base
    entrypoint: ["make", "spelling"]
    working_dir: /tests/django/docs
    user: root

  flake8:
    <<: *base
    entrypoint: flake8
